version: '3.8'

services:
  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 run:gunicorn_app
    volumes:
      - ./PoetryBackend:/app
      - ./PoetryBackend/logs:/app/logs
      - ./PoetryBackend/database:/app/database
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - LOG_DIR=/app/logs
      - DATABASE_DIR=/app/database

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  logs:
  database: